name: Unbound CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write  # Required to create a release.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha || github.sha }}

    - name: Read VERSION
      id: version
      run: |
        echo "VERSION=$(cat VERSION)"
        echo "version=$(cat VERSION)" >> $GITHUB_ENV

    - name: Debug VERSION
      run: echo "Using VERSION=${{ env.version }}"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Image (no push on PR)
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: ${{ github.event_name == 'push' }}
        build-args: |
          VERSION=${{ env.version }}
        tags: |
          chandanghosh/unbound-docker:${{ env.version }}
          chandanghosh/unbound-docker:latest

    - name: Check if release exists
      if: github.event_name == 'push'
      id: check_release
      run: |
        curl -s -o /dev/null -w "%{http_code}" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/repos/${{ github.repository }}/releases/tags/v${{ env.version }} \
        | grep -q 200 && echo "exists=true" >> $GITHUB_ENV || echo "exists=false" >> $GITHUB_ENV

    - name: Create GitHub Release
      if: github.event_name == 'push' && env.exists == 'false'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.version }}
        release_name: Release v${{ env.version }}
        draft: false
        prerelease: false
        body: |
          ## Changes in this release
          - Built and pushed Docker image for version `chandanghosh/unbound-docker:${{ env.version }}`
