name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Read version from VERSION file
    - name: Read VERSION
      id: version
      run: echo "version=$(cat VERSION)" >> $GITHUB_ENV

    # Set up QEMU for cross-compilation
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push the multi-arch image
    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: |
          chandanghosh/unbound-docker:${{ env.version }}
          chandanghosh/unbound-docker:latest

